services:
  - type: web
    name: transformer-model-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install python-dotenv==1.0.0
      pip install -r requirements.txt
    startCommand: |
      cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MODEL_NAME
        value: bert-base-uncased
      - key: UPLOAD_FOLDER
        value: uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: ALLOWED_EXTENSIONS
        value: csv,json,xls,xlsx
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
    healthCheckPath: /
    autoDeploy: true 